// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://j6pyq2el6rd4hfxf6jyxeasksy.appsync-api.eu-west-2.amazonaws.com/graphql',
          region: 'eu-west-2',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-aug7nx5jgvbjfksuzbllf2q5tu'
        }
    }
};

export default config;